# jekyll-seo-tag
title: Mason ACM
url: "http://new.masonacm.org/"
email: wmhsacm@gmail.com
description: William Mason High School's student chapter of the Association for Computing Machinery.
twitter:
  username: mason_acm
logo: /images/logo.png
social:
  links:
    - https://twitter.com/mason_acm
    - https://github.com/cravend/mason-acm-website

# jekyll-archives
jekyll-archives:
  enabled:
    - "categories"

# data page generator

page_gen-dirs: true
page_gen:
- data: teams
  name: name
  dir: teams

# general

paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:title"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-archives"
  - "jekyll-paginate"
  
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
