title: Mason ACM
url: "https://acm.masonhackclub.tech"
email: wmhsacm@gmail.com

# Default description in social shares for the jekyll-seo-tag gem
description: William Mason High School's student chapter of the Association for Computing Machinery.

# Social details for the jekyll-seo-tag gem
social:
  name: Mason ACM
  links:
    - https://twitter.com/mason_acm
    - https://github.com/cravend/mason-acm-website

twitter:
  username: mason_acm

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:title"

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  # - Facebook
  # - Google Plus
  # - Instagram
  # - LinkedIn
  # - Pinterest
  # - Tumblr
  - Twitter
  - YouTube
  # - RSS
