# jekyll-seo-tag
title: Mason ACM
url: "https://masonacm.org"
email: wmhsacm@gmail.com
description: >-
  Mason ACM is part of an international organization: ACM.
  ACM is an organization for computing professionals to deliver
  resources that advance computing as a science and a profession.
twitter:
  username: mason_acm
logo: /images/logo.png
social:
  links:
    - https://twitter.com/mason_acm
    - https://github.com/TheMasonACM/mason-acm-website

# jekyll-archives
jekyll-archives:
  enabled:
    - "categories"

# data page generator

page_gen-dirs: true
page_gen:
- data: teams
  name: name
  title: teamname
  dir: teams

# general

paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:title"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-archives"
  - "jekyll-paginate"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
